import { escapeHtml, formatDate } from "../core/utils.js";

export function renderEmailVerification({ user = {}, challenge = null, error = "", busy = false } = {}) {
  const verified = Boolean(user.emailVerified);
  const mode = challenge?.mode || (verified ? "REBIND" : "FIRST_BIND");
  return `<section class="page-stack account-flow"><button class="button button-secondary back-button" data-route="profile">← 返回我的</button>
    <header><span class="eyebrow">EMAIL SECURITY</span><h1 class="page-heading">${verified ? "换绑邮箱" : "绑定学校邮箱"}</h1><p class="page-caption">${verified ? `当前邮箱 ${escapeHtml(user.primaryEmailMasked || "已验证")}` : "完成邮箱验证后才能扫码或输入邀请码加入课程"}</p></header>
    ${error ? `<div class="notice auth-error">${escapeHtml(error)}</div>` : ""}
    <form id="email-verification-form" class="card"><div class="card-body page-stack">
      ${challenge ? `<div class="notice">验证码有效期至 ${formatDate(challenge.expiresAt)}。${mode === "REBIND" ? "请分别输入当前邮箱和新邮箱收到的验证码。" : "请输入新邮箱收到的验证码。"}</div>${mode === "REBIND" ? '<label class="field"><span>当前邮箱验证码</span><input name="currentEmailCode" inputmode="numeric" pattern="[0-9]{4,10}" maxlength="10" required></label>' : ""}<label class="field"><span>新邮箱验证码</span><input name="newEmailCode" inputmode="numeric" pattern="[0-9]{4,10}" maxlength="10" required></label><button class="button button-primary button-block" ${busy ? "disabled" : ""}>${busy ? "验证中…" : "完成验证"}</button><button class="button button-secondary button-block" type="button" data-action="restart-email-verification">重新填写邮箱</button>` : `<label class="field"><span>${verified ? "新学校邮箱" : "学校邮箱"}</span><input name="email" type="email" maxlength="254" placeholder="name@bnbu.edu.cn" required></label><button class="button button-primary button-block" ${busy ? "disabled" : ""}>${busy ? "发送中…" : "发送验证邮件"}</button>`}
    </div></form></section>`;
}

export function renderCourseJoin({ user = {}, token = "", preview = null, error = "", busy = false, scanning = false, allowPending = false } = {}) {
  if (!allowPending && !user.emailVerified) {
    return `<section class="page-stack account-flow"><button class="button button-secondary back-button" data-route="courses">← 返回课程</button><div class="card"><div class="card-body page-stack"><span class="eyebrow">EMAIL REQUIRED</span><h1 class="page-heading">请先验证邮箱</h1><p>未完成邮箱验证的账号不能扫码或输入邀请码加入课程。</p><button class="button button-primary" data-route="email">去验证邮箱</button></div></div></section>`;
  }
  return `<section class="page-stack account-flow"><button class="button button-secondary back-button" ${allowPending ? 'data-action="leave-public-join"' : 'data-route="courses"'}>← ${allowPending ? "返回邮箱登录" : "返回课程"}</button>
    <header><span class="eyebrow">JOIN COURSE</span><h1 class="page-heading">扫码或邀请码入课</h1><p class="page-caption">确认课程信息和本人学籍信息后直接加入教学班</p></header>
    ${error ? `<div class="notice auth-error">${escapeHtml(error)}</div>` : ""}
    ${scanning ? `<section class="card"><div class="card-body camera-panel"><video id="qr-camera" autoplay muted playsinline></video><p class="page-caption">请将课程二维码置于画面中央</p><button class="button button-secondary" data-action="stop-qr-scan">停止扫码</button></div></section>` : ""}
    ${preview ? `<section class="card"><div class="card-head"><h2 class="card-title">确认课程</h2></div><div class="card-body detail-facts"><div><span>课程</span><strong>${escapeHtml(preview.courseName)}</strong></div><div><span>课程代码</span><strong>${escapeHtml(preview.courseCode)}</strong></div><div><span>教学班</span><strong>${escapeHtml(preview.displayName)}</strong></div><div><span>任课老师</span><strong>${escapeHtml(preview.teacherDisplayName)}</strong></div><div><span>学期</span><strong>${escapeHtml(preview.semesterDisplayName)}</strong></div></div></section><form id="course-join-form" class="card"><div class="card-body page-stack"><input type="hidden" name="inviteToken" value="${escapeHtml(token)}"><label class="field"><span>姓名</span><input name="fullName" maxlength="100" value="${escapeHtml(user.fullName || "")}" required></label><label class="field"><span>学号</span><input name="studentNumber" maxlength="32" value="${escapeHtml(user.studentNumber || "")}" required></label><label class="field"><span>性别</span><select name="gender" required><option value="MALE" ${user.gender === "MALE" ? "selected" : ""}>男</option><option value="FEMALE" ${user.gender === "FEMALE" ? "selected" : ""}>女</option></select></label><label class="field"><span>入学年份</span><input name="gradeYear" type="number" min="1000" max="9999" value="${escapeHtml(user.gradeYear || "")}" required></label><button class="button button-primary button-block" ${busy ? "disabled" : ""}>${busy ? "加入中…" : "确认并加入课程"}</button></div></form>` : `<form id="invite-preview-form" class="card"><div class="card-body page-stack"><label class="field"><span>课程邀请码</span><input name="inviteToken" minlength="16" value="${escapeHtml(token)}" autocomplete="off" placeholder="请输入课程邀请码" required></label><div class="action-row"><button class="button button-secondary" type="button" data-action="start-qr-scan">扫描二维码</button><button class="button button-primary" ${busy ? "disabled" : ""}>${busy ? "查询中…" : "查看课程"}</button></div></div></form>`}
  </section>`;
}
