import { escapeHtml, formatDate } from "../core/utils.js";

const feedbackStatus = (value) => ({ OPEN: "已提交", IN_PROGRESS: "处理中", RESOLVED: "已回复", CLOSED: "已关闭" }[value] || value || "已提交");

export function renderHelp({ articles = [], error = "" } = {}) {
  return `<section class="page-stack"><button class="button button-secondary back-button" data-route="profile">← 返回我的</button><header><span class="eyebrow">HELP</span><h1 class="page-heading">帮助中心</h1><p class="page-caption">内容由 Backend /api/v1 实时提供</p></header>${error ? `<div class="notice auth-error">${escapeHtml(error)}</div>` : ""}<div class="page-stack">${articles.map((article) => `<details class="card"><summary class="card-head"><strong>${escapeHtml(article.title)}</strong><span class="badge">${escapeHtml(article.category)}</span></summary><div class="card-body help-copy">${String(article.bodyMarkdown || "").split(/\n{2,}/).map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join("")}</div></details>`).join("") || '<div class="card"><div class="card-body muted">当前没有已发布的帮助文章。</div></div>'}</div></section>`;
}

export function renderFeedback({ items = [], error = "", busy = false } = {}) {
  return `<section class="page-stack"><button class="button button-secondary back-button" data-route="profile">← 返回我的</button><header><span class="eyebrow">FEEDBACK</span><h1 class="page-heading">问题反馈</h1><p class="page-caption">反馈与公开回复均保存在 Backend</p></header>${error ? `<div class="notice auth-error">${escapeHtml(error)}</div>` : ""}<form id="feedback-form" class="card"><div class="card-body page-stack"><label class="field"><span>反馈类型</span><select name="category"><option value="BUG">功能问题</option><option value="SUGGESTION">产品建议</option><option value="ACCESSIBILITY">无障碍体验</option><option value="PRIVACY">隐私问题</option><option value="OTHER">其他</option></select></label><label class="field"><span>反馈内容</span><textarea name="content" minlength="1" maxlength="2000" required placeholder="请描述问题、发生页面与操作步骤"></textarea></label><button class="button button-primary button-block" ${busy ? "disabled" : ""}>${busy ? "提交中…" : "提交反馈"}</button></div></form><div class="record-list">${items.map((item) => `<article class="card"><div class="card-body page-stack"><div class="section-row"><strong>${escapeHtml(feedbackStatus(item.status))}</strong><time class="page-caption">${formatDate(item.createdAt)}</time></div><p>${escapeHtml(item.content)}</p>${item.publicReply ? `<div class="notice"><strong>官方回复</strong><br>${escapeHtml(item.publicReply)}</div>` : ""}</div></article>`).join("") || '<div class="card"><div class="card-body muted">暂无历史反馈。</div></div>'}</div></section>`;
}
