import { escapeHtml, formatDate, formatBytes, safeProofUrl } from "../core/utils.js";

export function validateExemption({ type, reason, proofs = [] }) {
  const errors = [];
  if (!["PHYSICAL_TEST","EXERCISE_CHECK_IN","SPECIAL_CIRCUMSTANCE"].includes(type)) errors.push("请选择申请类型");
  const length = String(reason || "").trim().length;
  if (length < 1 || length > 1000) errors.push("申请原因须为 1–1000 个字符");
  if (proofs.length > 20) errors.push("证明文件最多 20 个");
  return errors;
}

const exemptionTone = (status) => status === "已通过" ? "badge-success" : ["已驳回","需补材料","补材料"].includes(status) ? "badge-danger" : "badge-warning";

export function renderExemptions(items = []) {
  return `<section class="page-stack tool-page"><button class="button button-secondary back-button" data-route="profile">← 返回我的</button><header><span class="eyebrow">EXEMPTION</span><h1 class="page-heading">体育免测与免打卡申请</h1><p class="page-caption">800m / 1000m 申请、材料补交与审核记录</p></header><button class="button button-primary new-exemption" data-route="exemption-new">＋ 提交新申请</button><div class="section-row"><div><span class="eyebrow">APPLICATIONS</span><h2 class="section-heading">我的申请</h2></div><span class="badge">${items.length} 条</span></div><div class="record-list exemption-list">${items.map((item) => `<button class="record-card exemption-card" type="button" data-route="exemption/${escapeHtml(item.id)}" data-exemption-id="${escapeHtml(item.id)}"><div><strong>${escapeHtml(item.type)} 免测</strong><span class="badge ${exemptionTone(item.status)}">${escapeHtml(item.status)}</span></div><p>${escapeHtml(item.reason)}</p><span class="page-caption">${formatDate(item.createdAt)} · ${item.proofFiles?.length || 0} 个证明</span>${["需补材料","补材料"].includes(item.status) ? '<span class="exemption-action">补交证明 →</span>' : ""}</button>`).join("") || '<div class="card"><div class="card-body muted">你还没有提交过免测或免打卡申请。</div></div>'}</div></section>`;
}

export function renderExemptionDetail(item) {
  if (!item) return '<div class="card"><div class="card-body muted">申请不存在。</div></div>';
  const proofs = (item.proofFiles || []).map(safeProofUrl).filter(Boolean);
  return `<section class="page-stack tool-page"><button class="button button-secondary back-button" data-route="exemptions">← 返回我的申请</button><header><span class="eyebrow">APPLICATION DETAIL</span><h1 class="page-heading">${escapeHtml(item.type)} 申请详情</h1></header><section class="card"><div class="card-body page-stack"><div class="section-row"><h2 class="card-title">申请状态</h2><span class="badge ${exemptionTone(item.status)}">${escapeHtml(item.status)}</span></div><div class="detail-facts"><div><span>所属组织</span><strong>${escapeHtml(item.organization || "个人申请")}</strong></div><div><span>提交时间</span><strong>${formatDate(item.createdAt)}</strong></div><div><span>申请理由</span><strong>${escapeHtml(item.reason || "未填写")}</strong></div></div></div></section><section class="card"><div class="card-head"><h2 class="card-title">证明材料</h2></div><div class="card-body proof-grid">${proofs.map((url,index) => `<a class="proof-preview" href="${escapeHtml(url)}" target="_blank" rel="noopener"><img src="${escapeHtml(url)}" alt="免测证明 ${index + 1}" loading="lazy"></a>`).join("") || '<div class="upload-empty">尚未上传证明材料</div>'}</div></section><section class="card"><div class="card-head"><h2 class="card-title">处理意见</h2></div><div class="card-body"><p>${escapeHtml(item.reviewComment || "申请正在审核，暂无处理意见。")}</p></div></section>${["需补材料","补材料"].includes(item.status) ? `<button class="button button-primary" type="button" data-action="supplement-exemption" data-exemption-id="${escapeHtml(item.id)}">补交证明材料</button>` : ""}</section>`;
}

export function renderExemptionForm({ student = {}, enrollments = [], proofs = [], error = "", busy = false, supplementTarget = null } = {}) {
  const type = supplementTarget?.applicationType || supplementTarget?.type || "PHYSICAL_TEST";
  return `<section class="page-stack tool-page"><button class="button button-secondary back-button" data-route="${supplementTarget ? `exemption/${escapeHtml(supplementTarget.id)}` : "exemptions"}">← 返回申请记录</button><header><span class="eyebrow">${supplementTarget ? "SUPPLEMENT" : "NEW APPLICATION"}</span><h1 class="page-heading">${supplementTarget ? "补交证明材料" : "提交免测申请"}</h1><p class="page-caption">申请与证明材料统一提交到 Backend /api/v1</p></header>${error ? `<div class="notice risk-notice">${escapeHtml(error)}</div>` : ""}<form id="exemption-form" class="card exemption-form"><div class="card-body page-stack"><label class="field"><span>所属教学班</span><select name="enrollmentId" required>${enrollments.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === (supplementTarget?.enrollmentId || enrollments[0]?.id) ? "selected" : ""}>${escapeHtml(item.classSectionId)}</option>`).join("")}</select></label><label class="field"><span>申请类型</span><select name="type" ${supplementTarget ? "disabled" : ""}><option value="PHYSICAL_TEST" ${type === "PHYSICAL_TEST" ? "selected" : ""}>免体测</option><option value="EXERCISE_CHECK_IN" ${type === "EXERCISE_CHECK_IN" ? "selected" : ""}>免运动打卡</option><option value="SPECIAL_CIRCUMSTANCE" ${type === "SPECIAL_CIRCUMSTANCE" ? "selected" : ""}>特殊情况</option></select>${supplementTarget ? `<input type="hidden" name="type" value="${escapeHtml(type)}">` : ""}</label><label class="field"><span>申请原因</span><textarea name="reason" maxlength="1000" placeholder="请说明真实原因">${escapeHtml(supplementTarget?.reason || "")}</textarea></label><label class="upload-picker"><input id="exemption-proof-picker" type="file" accept="image/jpeg,image/png" multiple><span>＋ 添加证明图片</span></label><div class="exemption-upload-list">${proofs.map((proof) => `<div><span><strong>${escapeHtml(proof.file?.name || "证明文件")}</strong><small>${formatBytes(proof.size)}</small></span><button type="button" class="text-action" data-action="remove-exemption-upload" data-upload-id="${escapeHtml(proof.id)}">删除</button></div>`).join("") || '<p class="page-caption">尚未选择证明文件（最多 20 个）</p>'}</div><button class="button button-primary button-block" ${busy || !enrollments.length ? "disabled" : ""}>${busy ? "提交中…" : supplementTarget ? "提交补充材料" : "提交免测申请"}</button></div></form></section>`;
}
