import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { verifyContractBinding } from "../scripts/verify-contract.mjs";

// The fingerprint published with Backend Contract 2.0.2. It is quoted here on
// purpose: a sync that silently edits the snapshot must fail this test instead
// of updating its own expectation.
const PUBLISHED_SHA256 =
  "853e7f5efadb10dcbbe0f446c4c60962ce2fd864360a156343b5740d0c1761a4";
const PUBLISHED_VERSION = "2.0.2-contract";

test("the pinned snapshot is the published Contract 2.0.2 release artifact", async () => {
  const report = await verifyContractBinding();

  assert.deepEqual(report.problems, []);
  assert.equal(report.sha256, PUBLISHED_SHA256);
  assert.equal(report.declaredVersion, PUBLISHED_VERSION);
  assert.equal(report.descriptor.contractVersion, PUBLISHED_VERSION);
  assert.equal(report.byteLength, 323046);
  assert.deepEqual(report.counts, { paths: 109, operations: 126, schemas: 288 });
});

test("the generated types are the ones openapi-typescript emits for that snapshot", async () => {
  // `npm run contract:check` regenerates and diffs; this guards the cheap
  // giveaway that the file was hand-edited or left behind by an older sync.
  const generated = await readFile(
    new URL("../app/openapi.generated.ts", import.meta.url),
    "utf8",
  );

  assert.match(generated, /This file was auto-generated by openapi-typescript/);
  assert.match(
    generated,
    /Submit a draft and atomically create a system VALID ReviewRecord/,
  );
  assert.match(
    generated,
    /Append an INVALID decision for a current VALID record, or resolve legacy PENDING/,
  );
});

test("the client never re-derives a review state the Backend owns", async () => {
  const teacherData = await readFile(
    new URL("../app/teacher-data.ts", import.meta.url),
    "utf8",
  );

  // Every audit state must be read from the server's currentReview projection.
  assert.match(teacherData, /const result = record\.currentReview\?\.result;/);
  assert.match(teacherData, /if \(result === "VALID"\) return "valid";/);
  assert.match(teacherData, /if \(result === "INVALID"\) return "invalid";/);
  assert.match(
    teacherData,
    /upper === "ACTIVE" \|\| upper === "UPCOMING"/,
  );
});
